apiVersion: apps/v1
kind: Pod
metadata:
  name: nodeselector
  labels:
    app: nodeselector
spec:
  nodeSelector:
    topology.kubernetes.io/zone: "us-east-1a"
  containers:
    - name: nginx
      image: nginx:1.24.0
