apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
   app-name: test
  namespace: expense
spec:
  containers:
  - name: nginx
    image: nginx
   
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
   app-name: test
  namespace: expense
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app-name
            operator: In
            values:
            - test
  containers:
  - name: nginx
    image: nginx
   

