apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: test
  namespace: expense
spec:
  containers:
  - name: nginx
    image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: expense
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - test
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx
   

