#kubectl taint nodes ip-192-168-31-201.ec2.internal hardware=gpu:NoSchedule

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: expense
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone: "us-east-1a"
  containers:
  - name: nginx
    image: nginx
   
