apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: expense
spec:
  nodeSelector:
    topology.kubernetes.io/zone: "us-east-1a"
  containers:
  - name: nginx
    image: nginx
   
tolerations:
- key: "hardware"
  operator: "Equal"
  value: "gpu"
  effect: "NoSchedule"
